name: ✨ Feature Request
description: Sugerir uma nova funcionalidade
title: '[FEATURE]: '
labels: ['enhancement', 'needs-triage']

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma feature! Por favor, preencha as informações abaixo.

  - type: textarea
    id: problem
    attributes:
      label: Problema que Resolve
      description: Existe algum problema relacionado? Descreva.
      placeholder: 'Ex: Eu fico frustrado quando...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução que você gostaria
      placeholder: 'Eu gostaria que...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva alternativas que você considerou

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Mockups, exemplos, referências, etc.
